/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import acceso_datos.PoblacionJpaController;
import java.util.Calendar;
import java.util.Date;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JCheckBox;
import modelo.Poblacion;
import java.util.*;

/**
 *
 * @author jesus
 */
public class Principal extends javax.swing.JPanel {
        private Corridass corridas;
          private PoblacionJpaController Poblaciones;
          private EntityManagerFactory emf;
    /**
     * Creates new form Principal
     */
    public Principal() {
        emf = Persistence.createEntityManagerFactory("GestionAsientosAutobusesPU");
        Poblaciones= new PoblacionJpaController(emf);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        origenDestino = new comod.OrigenDestino();
        todaslasCorridas = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fecha = new com.toedter.calendar.JDateChooser();

        origenDestino.setCiudades(new String[] {});

        todaslasCorridas.setText("jCheckBox1");
        todaslasCorridas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todaslasCorridasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("busqueda corrida");

        jLabel2.setText("Origen");

        jLabel3.setText("Destino");

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(todaslasCorridas))
                .addGap(233, 233, 233))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(origenDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(origenDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(todaslasCorridas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
        );

        List<Poblacion> listaPoblaciones=Poblaciones.findPoblacionEntities();
        String ciudades[]=new String[listaPoblaciones.size()];
        for(int i=0;i<listaPoblaciones.size();i++){
            Poblacion p=listaPoblaciones.get(i);
            ciudades[i]=p.getNombre();
        }
        origenDestino.setCiudades(ciudades);
    }// </editor-fold>//GEN-END:initComponents

    private void todaslasCorridasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todaslasCorridasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todaslasCorridasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cOrigen=origenDestino.getOrigen();
        String cDestino=origenDestino.getDestino();
        System.out.println("El origen es: "+cOrigen+ " y el Destino es: "+cDestino);
        corridas.seleccionarCorrida(cOrigen, cDestino, fecha.getDate());
    }//GEN-LAST:event_jButton1ActionPerformed

     Calendar fechaC = Calendar.getInstance();
    public int mes(){
         int mes = fechaC.get(Calendar.MONTH) + 1;
         return mes;
        }
     public int dia(){
           int dia = fechaC.get(Calendar.DAY_OF_MONTH);
         return dia;
        }
      public int anio(){
            int anio = fechaC.get(Calendar.YEAR);
            return anio;
        }
      public  Date getActualDate(){
             return fechaC.getTime();     
        }
      public void prueba(){
      
      }

      public JCheckBox getTodaslasCorridas(){
          return todaslasCorridas;
      }
      public void conectaCorridas(Corridass corridas){
          this.corridas=corridas;
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private comod.OrigenDestino origenDestino;
    private javax.swing.JCheckBox todaslasCorridas;
    // End of variables declaration//GEN-END:variables
}
