/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import compiresasi.IReservaAsiento;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesus
 */
public class Reserva extends javax.swing.JPanel {
   private AsignarPasaje pasaje;
    private DefaultTableModel modeloT;
    private Corridass corridas;
    /**
     * Creates new form Reserva
     */
    public Reserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selAsi = new compiresasi.IReservaAsiento();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Seleccionar Asientos");

        selAsi.setDistribucion("Horizontal");
        selAsi.setNumAsientos(36);
        selAsi.setOpaque(false);

        jButton1.setText(" Boletos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selAsi, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(selAsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ArrayList<Integer> nasi= selAsi.getSeleccionados();
        int na=nasi.size();
        //JComboBox combotipo=createComboTipo();
       
        String enca[]={"Asiento","Nombre Pasajero","Tipo de Pasajero"};
        Object datos[][]= new Object[na][3];
        modeloT=new DefaultTableModel(datos,enca);
        for(int a=0;a<na;a++){
            datos[a][0]=nasi.get(a);
            datos[a][1]=new String("");
            datos[a][2]= new String("Adulto");
            modeloT= new DefaultTableModel(datos,enca);
            pasaje.getNombres().actualizarDatos(modeloT);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public IReservaAsiento getSelAsi(){
    return selAsi;
}

    public void conectaAsignarPasaje(AsignarPasaje pasaje){
    this.pasaje=pasaje;
    }
    public DefaultTableModel getModelDatos(){
    return modeloT;
    }

    public void conectaCorrida(Corridass corridas){
        this.corridas=corridas;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private compiresasi.IReservaAsiento selAsi;
    // End of variables declaration//GEN-END:variables
      
    


}
