/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import GestionCorrida.AutobusJpaController;
import GestionCorrida.CorridasJpaController;
import GestionCorrida.MunicipioJpaController;
import GestionCorrida.PoblacionJpaController;
import GestionCorrida.exceptions.NonexistentEntityException;
import Modelo.Autobus;
import Modelo.Corridas;
import Modelo.Municipio;
import Modelo.Poblacion;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesus
 */
public class GestionCorrida extends javax.swing.JDialog {
      private EntityManagerFactory emf;
    private AutobusJpaController NewAutobus;
    private Autobus AutobusSelect;
    private PoblacionJpaController NewPoblacion;
    private Poblacion PoblacionSelect;
    private MunicipioJpaController  Municipios;
    private List<Municipio> municipios;
    private List<Poblacion> poblaciones;
    private List<Autobus> lista;
    private CorridasJpaController NewCorrida;
    private Corridas CorridaSelect;
    /**
     * Creates new form GestionCorrida
     */
    public GestionCorrida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
          emf=Persistence.createEntityManagerFactory("GestionCorridasPU");
        NewAutobus= new AutobusJpaController(emf);
        NewPoblacion=new PoblacionJpaController(emf);
        NewCorrida= new CorridasJpaController(emf);
        Municipios= new MunicipioJpaController (emf);
        municipios = Municipios.findMunicipioEntities();
        poblaciones= NewPoblacion.findPoblacionEntities();
        lista=NewAutobus.findAutobusEntities();
        initComponents();
        llenarTabla1();//Tabla de Autobuses
        llenarTabla2();
        NuevasCorridas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Corri = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Origen = new javax.swing.JComboBox<>();
        Destino = new javax.swing.JComboBox<>();
        Tipo = new javax.swing.JComboBox<>();
        Fecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        costo = new Micampo.MiCampo();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pobla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        ComboMuni = new javax.swing.JComboBox<>();
        PoblaText = new ComTitDato.CompTitDato();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TipoAutobus = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        Bus = new ComTitDato.CompTitDato();
        Cupo = new ComTitDato.CompTitDato();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Agregar Corrida");

        Corri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Corri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CorriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Corri);

        jLabel2.setText("Origen:");

        jLabel3.setText("Destino:");

        jLabel4.setText("Autobus:");

        jLabel5.setText("Fecha:");

        jLabel6.setText("Costo:");

        Destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinoActionPerformed(evt);
            }
        });

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        costo.setLongitud(6);
        costo.setTipo("ENTERO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Origen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(23, 23, 23))
        );

        for(Poblacion p: poblaciones){
            Origen.addItem(p.getNombre());
        }
        for(Poblacion p: poblaciones){
            Destino.addItem(p.getNombre());
        }
        for(Autobus a:lista){
            Tipo.addItem(a.getTipo());
        }
        Calendar c = Calendar.getInstance();
        Fecha.setDate(c.getTime());
        Fecha.setMinSelectableDate(c.getTime());

        jTabbedPane1.addTab("Corridas", jPanel2);

        Pobla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Pobla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PoblaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Pobla);

        jLabel7.setText("Nueva Poblacion");

        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Modificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Eliminar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Limpar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        ComboMuni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Municipio" }));

        PoblaText.setLongitud(25);
        PoblaText.setText("");
        PoblaText.setTipo("TEXTO");
        PoblaText.setTitulo("Poblacion");

        jLabel8.setText("Municipio:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(300, 300, 300))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PoblaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addComponent(ComboMuni, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboMuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(PoblaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(24, 24, 24))
        );

        for(Municipio m: municipios){
            ComboMuni.addItem(m.getNombre());
        }

        jTabbedPane1.addTab("Poblacion", jPanel3);

        TipoAutobus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Autobus", "Tipo", "Asientos"
            }
        ));
        TipoAutobus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TipoAutobusMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TipoAutobus);

        jLabel9.setText("Autobus");

        Bus.setLongitud(25);
        Bus.setTipo("TEXTO");
        Bus.setTitulo("Autobus");

        Cupo.setLongitud(5);
        Cupo.setTipo("ENTERO");
        Cupo.setTitulo("Asientos");

        jButton9.setText("Nuevo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Actualizar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Eliminar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Limpar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(Cupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(302, 302, 302))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11)
                        .addGap(7, 7, 7)
                        .addComponent(jButton12)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(Bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Autobus", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Poblacion p= new Poblacion();
        if(!PoblaText.getDato().equals("")&& ComboMuni.getSelectedIndex()>0)
            try{
                p.setNombre(PoblaText.getDato());
                p.setIdmpo(municipios.get(ComboMuni.getSelectedIndex()-1));
                NewPoblacion.create(p);
                Aviso("Agregado Correctamente:" +p.getNombre());
                limpiar2();
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         if(AutobusSelect!=null){
            try {
                NewAutobus.destroy(AutobusSelect.getIdautobus());
                Aviso("Datos del autobus eliminados");
                llenarTabla3();
                limpiar3();
            } catch (NonexistentEntityException ex) {

            }

        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Corridas p= new Corridas();
        if(!costo.getDato().equals("")&& (Origen.getSelectedIndex()!=Destino.getSelectedIndex()) &&Origen.getSelectedIndex()>0 && Destino.getSelectedIndex()>0 )
            try{
                p.setOrigen(poblaciones.get(Origen.getSelectedIndex()-1));
                p.setDestino(poblaciones.get(Destino.getSelectedIndex()-1));
                p.setAutobus(lista.get(Tipo.getSelectedIndex()));
                p.setCosto(Integer.parseInt(costo.getDato()));
                p.setFechaHora(Fecha.getDate());
                NewCorrida.create(p);
                Aviso("Se ha insertado correctamente la Corrida");
                limpiar1();
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PoblaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PoblaMouseClicked
        // TODO add your handling code here:
         int filaPulsada = Pobla.getSelectedRow();
        //Si se ha pulsado una fila
        if(filaPulsada>=0){
            //Se recoge el id de la fila marcada
            int idPoblacion = Integer.parseInt("" + Pobla.getValueAt(filaPulsada,0));
            PoblacionSelect = NewPoblacion.findPoblacion (idPoblacion);
            PoblaText.setText(PoblacionSelect.getNombre());
            for(int j=0;j<municipios.size();j++){
                Municipio m= municipios.get(j);
                if(m.getIdmpo()== PoblacionSelect.getIdmpo().getIdmpo()){
                    ComboMuni.setSelectedIndex(j+1);
                    break;
                }
            }

        }
    }//GEN-LAST:event_PoblaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(CorridaSelect!=null)
           if(!costo.getDato().equals("")&& (Origen.getSelectedIndex()!=Destino.getSelectedIndex()) &&Origen.getSelectedIndex()>0 && Destino.getSelectedIndex()>0 )
            try{
                CorridaSelect.setOrigen(poblaciones.get(Origen.getSelectedIndex()-1));
                CorridaSelect.setDestino(poblaciones.get(Destino.getSelectedIndex()-1));
                CorridaSelect.setAutobus(lista.get(Tipo.getSelectedIndex()));
                CorridaSelect.setCosto(Integer.parseInt(costo.getDato()));
                CorridaSelect.setFechaHora(Fecha.getDate());
                NewCorrida.edit(CorridaSelect);
                Aviso("Se ha actualizado correctamente");
                limpiar1();
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(CorridaSelect!=null)
            try {
                NewCorrida.destroy(CorridaSelect.getIdcorrida());
                Aviso("Se eliminó correctamente");
                limpiar1();
            } catch (NonexistentEntityException ex) {

            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        limpiar1();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(PoblacionSelect!=null)
            if(!PoblaText.getDato().equals(""))
            try{
                PoblacionSelect.setNombre(PoblaText.getDato());
                PoblacionSelect.setIdmpo(municipios.get(ComboMuni.getSelectedIndex()-1));
                NewPoblacion.edit(PoblacionSelect);
                Aviso("Información Actualizada,\n de la Población:" +PoblacionSelect.getNombre());
                limpiar2();
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(PoblacionSelect!=null)
             try{
                NewPoblacion.destroy(PoblacionSelect.getIdpob());
                Aviso("Se ha elimnado correctamente,\n de la Población:" +PoblacionSelect.getNombre());
                limpiar2();
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        limpiar2();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void CorriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorriMouseClicked
        // TODO add your handling code here:
        int filaPulsada =Corri.getSelectedRow();
        //Si se ha pulsado una fila
        if(filaPulsada>=0){
            //Se recoge el id de la fila marcada
            int idCorrida=Integer.parseInt(""+Corri.getValueAt(filaPulsada,0));
            CorridaSelect= NewCorrida.findCorridas(idCorrida);
            Fecha.setDate(CorridaSelect.getFechaHora());
            costo.setText(""+CorridaSelect.getCosto());
               //Seleccinar Origen
            for(int j=0;j< poblaciones.size();j++){
                Poblacion m= poblaciones.get(j);
                if(m.getIdpob()== CorridaSelect.getOrigen().getIdpob()){
                    Origen.setSelectedIndex(j+1);
                    break;
                }
            }
            //Seleccionar el destino
            for(int j=0;j<poblaciones.size();j++){
                Poblacion m= poblaciones.get(j);
                if(m.getIdpob()== CorridaSelect.getDestino().getIdpob()){
                    Destino.setSelectedIndex(j+1);
                    break;
                }
            }
            //Tipo de Autobus
            for(int j=0;j< lista.size();j++){
                Autobus a= lista.get(j);
                if(a.getIdautobus()== CorridaSelect.getAutobus().getIdautobus()){
                    Tipo.setSelectedIndex(j);
                    break;
                }
            } 

        }
    }//GEN-LAST:event_CorriMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Autobus autob= new Autobus();
        autob.setTipo(Bus.getDato());
        autob.setAsientos(Integer.parseInt(Cupo.getDato()));
        if(!Bus.getDato().equals("") && !Cupo.getDato().equals(""))
        try{
            NewAutobus.create(autob);
            limpiar3();
            Aviso("Se registro correctamente la información del Autobús");
            llenarTabla3();
        }catch(Exception e){}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(AutobusSelect!=null){
            AutobusSelect.setTipo(Bus.getDato());
            AutobusSelect.setAsientos(Integer.parseInt(Cupo.getDato()));
            if(!Bus.getDato().equals("") && !Cupo.getDato().equals(""))
            try{
                NewAutobus.edit(AutobusSelect);
                Aviso("Informacion autobus actualizada");
                limpiar3();
                llenarTabla3();
            }catch(Exception e){}
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void TipoAutobusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TipoAutobusMouseClicked
        // TODO add your handling code here:
        int filaPulsada = TipoAutobus.getSelectedRow();
        //Si se ha pulsado una fila
        if(filaPulsada>=0){
            //Se recoge el id de la fila marcada
            int idAutobus=Integer.parseInt(""+TipoAutobus.getValueAt(filaPulsada,0));
            AutobusSelect= NewAutobus.findAutobus(idAutobus);
            Cupo.setText(""+AutobusSelect.getAsientos());
            Bus.setText(AutobusSelect.getTipo());
        }
    }//GEN-LAST:event_TipoAutobusMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        limpiar3();
        llenarTabla3();
    }//GEN-LAST:event_jButton12ActionPerformed

   // Tabla de corridas
    public void llenarTabla1(){
    //Metodo para agregar registros a la tabla Corridas
    List<Poblacion> poblaciones=NewPoblacion.findPoblacionEntities();
    List<Autobus> tipoA=NewAutobus.findAutobusEntities();
    Random r = new Random();
    SimpleDateFormat  formatoFecha= new SimpleDateFormat("dd/MM/yyyy HH:mm");
    int dia=r.nextInt(20)+8;
    int mes=r.nextInt(5)+6;
    int year=r.nextInt(20)+2020;
    int min=r.nextInt(40)+10;
    int ho=r.nextInt(10)+10;
    int costo=120;
    for(Poblacion p:poblaciones){
        for(Poblacion p2:poblaciones){
           Corridas corrida = new Corridas();
            if(!p.getNombre().equalsIgnoreCase(p2.getNombre())){
               corrida.setOrigen(p);
               corrida.setDestino(p2);
               int num=r.nextInt(tipoA.size()-1);
               corrida.setAutobus(tipoA.get(num));
               corrida.setCosto(costo);
               costo=costo+23;
               try {
                   Date fecha=formatoFecha.parse(dia+"/"+mes+"/"+year+" "+ho+":"+min);
                     dia=r.nextInt(20)+8;
                     mes=r.nextInt(5)+6;
                     year=r.nextInt(20)+2020;
                     min=r.nextInt(40)+10;
                     ho=r.nextInt(10)+10;
                 corrida.setFechaHora(fecha);
                 NewCorrida.create(corrida);
                 
               } catch (ParseException ex) {
                   Logger.getLogger(GestionCorrida.class.getName()).log(Level.SEVERE, null, ex);
               }
                    System.out.println(corrida);
                
            }
            
        }
    }
    
}
    //Tabla de Autobus
    public void llenarTabla3(){
     String encabezados[]=new String [] { "Autobús", "Tipo", "Asientos"};
      List<Autobus> autobuses=NewAutobus.findAutobusEntities();
      String[][]matriz=new String[autobuses.size()][3];
      for(int i=0;i<autobuses.size();i++){
          Autobus a=autobuses.get(i);
          matriz[i][0]=""+a.getIdautobus();
          matriz[i][1]=a.getTipo();
          matriz[i][2]=""+a.getAsientos();
      }
   DefaultTableModel modelo= new DefaultTableModel(matriz,encabezados);
   TipoAutobus.setModel(modelo);
    }
    // Tabla de poblacion
    public void llenarTabla2(){
     String encabezados[]=new String [] { "Poblacion", "Nombre", "Municipio"};
      List<Poblacion> poblaciones = NewPoblacion.findPoblacionEntities();
      String[][]matriz=new String[poblaciones.size()][3];
      for(int i=0;i<poblaciones.size();i++){
          Poblacion a=poblaciones.get(i);
          matriz[i][0]=""+a.getIdpob();
          matriz[i][1]=a.getNombre();
          matriz[i][2]=a.getIdmpo().getNombre();
      }
            DefaultTableModel modelo= new DefaultTableModel(matriz,encabezados);
             Pobla.setModel(modelo);
    }
    
    public void TablaPoblacion(){
     String encabezados[]=new String [] { "Poblacion", "Nombre", "Municipio"};
      List<Poblacion> poblaciones=NewPoblacion.findPoblacionEntities();
      String[][]matriz=new String[poblaciones.size()][3];
      for(int i=0;i<poblaciones.size();i++){
          Poblacion a=poblaciones.get(i);
          matriz[i][0]=""+a.getIdpob();
          matriz[i][1]=a.getNombre();
          matriz[i][2]=a.getIdmpo().getNombre();
      }
          DefaultTableModel modelo= new DefaultTableModel(matriz,encabezados);
          Pobla.setModel(modelo);
    }
    
    public void NuevasCorridas(){
    SimpleDateFormat  formatoFecha= new SimpleDateFormat("dd/MM/yyyy");
    String encabezados[]=new String [] { "Corrida", "Origen", "Destino", "Autobus", "Fecha", "Costo"};
     List<Corridas> corridas=NewCorrida.findCorridasEntities();
      String[][]matriz=new String[corridas.size()][6];
      for(int i=0;i<corridas.size();i++){
          Corridas a=corridas.get(i);
          matriz[i][0]=""+a.getIdcorrida();
          matriz[i][1]=a.getOrigen().getNombre();
          matriz[i][2]=a.getDestino().getNombre();
          matriz[i][3]=a.getAutobus().getTipo();
          matriz[i][4]=formatoFecha.format(a.getFechaHora());
          matriz[i][5]=""+a.getCosto();
      }
            DefaultTableModel modelo= new DefaultTableModel(matriz,encabezados);
            Corri.setModel(modelo);
    
    }
    
    public void Aviso(String mensaje){
    JOptionPane.showMessageDialog(null,mensaje);
    }
     
    public void limpiar1(){
    Origen.setSelectedIndex(0);
    Destino.setSelectedIndex(0);
    Calendar c=Calendar.getInstance();
    Fecha.setDate(c.getTime());
    costo.setText("");
    Tipo.setSelectedIndex(0);
    mostrarCorridas();
    }
    
    public void limpiar2(){
    PoblaText.setText("");
    ComboMuni.setSelectedIndex(0);
    TablaPoblacion();
    }
    
    public void limpiar3(){
    Cupo.setText("");
    Bus.setText("");
    }
    
    public void mostrarCorridas(){
    SimpleDateFormat  formatoFecha= new SimpleDateFormat("dd/MM/yyyy");
    String encabezados[]=new String [] {
        "idCorrida", "Origen", "Destino", "Tipo Autobus", "Fecha", "Costo"
    };
     List<Corridas> corridas=NewCorrida.findCorridasEntities();
      String[][]matriz=new String[corridas.size()][6];
      for(int i=0;i<corridas.size();i++){
          Corridas a=corridas.get(i);
          matriz[i][0]=""+a.getIdcorrida();
          matriz[i][1]=a.getOrigen().getNombre();
          matriz[i][2]=a.getDestino().getNombre();
          matriz[i][3]=a.getAutobus().getTipo();
          matriz[i][4]=formatoFecha.format(a.getFechaHora());
          matriz[i][5]=""+a.getCosto();
      }
   DefaultTableModel modelo= new DefaultTableModel(matriz,encabezados);
   Corri.setModel(modelo);
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionCorrida dialog = new GestionCorrida(new javax.swing.JFrame(), true);
                dialog.setLocationRelativeTo(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComTitDato.CompTitDato Bus;
    private javax.swing.JComboBox<String> ComboMuni;
    private javax.swing.JTable Corri;
    private ComTitDato.CompTitDato Cupo;
    private javax.swing.JComboBox<String> Destino;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JComboBox<String> Origen;
    private javax.swing.JTable Pobla;
    private ComTitDato.CompTitDato PoblaText;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JTable TipoAutobus;
    private Micampo.MiCampo costo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
